// Generated by https://quicktype.io

export interface ICategoriesResponse {
  results: IResults;
}

export interface IResults {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: ICategory[];
}

export interface ICategory {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}
